### ISSUE TITLE
Solution is not split into multiple classes

### ISSUE THREAD

**Issue by SPR999** [drydev/WizBangSuperSudokuSlayer#3]
By not splitting the code into multiple classes the solution cant be easily extended by only modifying one class 

Additionally, you cant reuse the code you have made for other projects

**Comment by drydev** [comment]
Resolved with new [commit](https://github.com/drydev/WizBangSuperSudokuSlayer/commit/bec9c83387d0cf964a8ab2e7d6c7e1c63b49e86a)

**Comment by SPR999** [comment]
<3
