### ISSUE TITLE
CSV to sudoku class does more than just convert CSV to 2d array

### ISSUE THREAD

**Issue by SPR999** [drydev/WizBangSuperSudokuSlayer#7]
The general coding principal SOLID should have been followed in essence one class one purpose. As an example this class could be split into 3 different classes one for getting user input, one for making a 2d grid, the last one for loading files. Put differently programming is like making lego blocks the you want to have a bunch of different types of blocks (Single purpose classes) and then combine them to make a house (program).

**Comment by drydev** [comment]
Resolved by latest [commit](https://github.com/drydev/WizBangSuperSudokuSlayer/commit/35f6a2cce8c7d42e85aaeffa93c89a7a3114620d)
